---
title: "Final Project Proposal"
author: "Talha Muhammad, Sharon Morris, Ka-Man Chan & Marco Siquera Campos"
date: "November 16, 2016"
output: html_document
---

## Final Project Proposal

### Overview 
We would like to understand through different sources the reasons for the variation in real estate prices in New York City - particularly the Bronx. We would seek to understand how have the sale property prices (or rental) have changed through out the city and the causes behind it.  

### Data sources
We plan on using the following data sources:     

####Real Estate Data (API)      

 1. Zillow API's or Trulia's data using webscraping provide data on comparable properties and market rates and data is available at the individual property level. The API limits calls to 1000 calls per day.         
 2. Zillow provides neighborhood boundaries     
 3. Neighborhood demographic information available from the Census (available via API and CSV)       
 
#### CSV data sources
 4. Incident level data on Criminal complaints,       
 
**Zillow API data**
http://www.zillow.com/howto/api/GetDeepSearchResults.htm

We will supplement our analysis with other data sources as needed. 

### Approach
Take property level information from Trulia (through webscraping) or Zillow API. The data has a variety of interesting variables including comparables. Match it with crime data and demographic information. This will be done for the Bronx in New York city.


Develop cross sectional regressions and / or tree based approaches to estimate "true value" based on the characteristics. 

**We need to add here? What is the goal of this analysis?** 

#### Option 1
*Are we trying to identify under valued and or over valued properties - if so - we will need to assume or identify some properties that are "correctly priced". For the purposes of this analysis we might randomly assume that (i.e. we assume some are correctly priced and the rest are not) - is there a better way of doing that?.  

#### Option 2
Identify how different characteristics of property types are valued - using regression or other approach. Then develop a comparison - say one bedrooms - with different characteristics are worth by different neighborhood 

### Visualization
- Develop charts and visualization in ggplot;
- Resources allow develop visualization in RShiny. 

### Outputs Requirements
- Two Different data sources (eg. csv and api)
- Includes one data transformation
- One statistical analysis & graphical analysis validates your data
- One graphic & one statistical analysis that supports your conclusions 
- One feature we did not cover in class


